name: Execution CI

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  
jobs:
  deploy-dev:
    uses: PRUEBA-INTERNA-001/chi-GitHub-Templates/.github/workflows/linuxBash-ci.yml@main
    with:
      deploy_platform: 'linux'
      path_destino: ${{ vars.PATH_DESTINO }}
      servidores: ${{ vars.SERVIDORES }}
      mask_include_files: ${{ vars.MASK_INCLUDE_FILES }}
      environment: "desarrollo"
    secrets: inherit