name: Execution CI

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  
jobs:
  deploy-dev:
    uses: PRUEBA-INTERNA-001/chi-GitHub-Templates/.github/workflows/linuxBash-ci.yml@main
    with:
      deploy_platform: 'linux'
      path_destino: '/tmp'
      servidores: 'server-a'
      mask_include_files: 'etc/ data/'
      environment: "desarrollo"
    secrets: inherit
