name: Execution release

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  
jobs:
  deploy-dev:
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/linuxBash-ci.yml@main
    with:
      environment: "desarrollo"
      create_release: true
    secrets: inherit
